### ISSUE TITLE
doesn't work.... :-/

### ISSUE THREAD

**Issue by NorFonts** [fkretlow/fontforge-smufl#1]
Hi,

Thanks for sharing this nice script but it doesn't work for me. I'm on macOS Catalina, I use FontFonrge v20200314. When I Execute script... t I get this message:

```
/Users/Nor/Desktop/bm/ff_smufl_metadata.py line: 4 Unterminated ff_statement
Called from...
 ScriptDlg: line 1
```

Thanks for any corrections and advice.

**Comment by fkretlow** [comment]
Hmm. That doesn't make much sense. Line 4 is part of the docstring and should be ignored.

Are you running the script from inside Fontforge? If so, don't, and please try running it with a stand-alone Python interpreter that has access to the fontforge module. (Normally there's an executable `ffpython` somewhere in the app folder.)

**Comment by fkretlow** [comment]
Since there’s been no further comment I assume that this is no longer an issue. Closing this now.
